FROM ruby:3.4.3

RUN apt-get update -qq && apt-get install -y build-essential sqlite3 && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN groupadd --system --gid 1000 dev && \
  useradd dev --uid 1000 --gid 1000 --create-home --shell /bin/bash

WORKDIR /auth_api

COPY Gemfile ./Gemfile
COPY Gemfile.lock ./Gemfile.lock

RUN bundle install

COPY --chown=dev:dev . .

EXPOSE 3001

USER dev:dev

RUN bundle exec rails db:create db:migrate

CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3001"]
