apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth_api
  nemaspace: crafts-dev
  labels:
    app: auth_api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth_api
  template:
    metadata:
      labels:
        app: auth_api
    spec:
      containers:
        - name: auth_api
          image: auth_api:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
