apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: crafts-dev
  labels:
    app: auth-api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: auth-api:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: RAILS_ENV
              value: development
            - name: PORT
              value: "3001"
            - name: RAILS_DEVELOPMENT_HOSTS
              value: "auth-api.local"
