FROM node:22.15

RUN apt-get update

RUN groupadd --system --gid 1001 webdev && \
  useradd webdev --uid 1001 --gid 1001 --create-home --shell /bin/bash

WORKDIR /webapp

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

COPY --chown=webdev:webdev . .

EXPOSE 3000

CMD ["npm", "run", "dev"]

